# This tries to emulate pure ZSH prompt:
# https://github.com/sindresorhus/pure

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration
$python$conda$character"""

add_newline = true

[directory]
style = "blue"
truncation_length = 2
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1

[character]
format = "$symbol "
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"

[username]
style_root = 'red bold'
style_user = 'bold white'
format = "[$user](style) "
show_always = false

[conda]
style = "bright-black"
format = "[$environment]($style) "

[python]
format = "[$virtualenv]($style)"
style = "bright-black"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"
stashed = "≡"
conflicted = " "
untracked = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
