name: Labeler - pull requests

on:
  pull_request_target:

jobs:
  labeling:
    name: Setting labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setting labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
